/* Veilfall service worker — generated by build_pwa.py, do not hand-edit.
   Cache-first for everything: the game is a fixed set of files and must run
   with no network at all. A new deploy changes this file (the version below is
   a hash of every file), the browser notices on the next online launch,
   installs the new set alongside the old one, and switches over. */
const VERSION = '953b8209df36';
const CACHE = 'veilfall-' + VERSION;
const PRECACHE = [
  "./",
  "./assets/backgrounds/castle.png",
  "./assets/backgrounds/desert.png",
  "./assets/backgrounds/event_chest.png",
  "./assets/backgrounds/event_merchant.png",
  "./assets/backgrounds/event_shrine.png",
  "./assets/backgrounds/event_traveler.png",
  "./assets/backgrounds/goddess.png",
  "./assets/backgrounds/home.png",
  "./assets/backgrounds/montage_board.png",
  "./assets/backgrounds/montage_hunt.png",
  "./assets/backgrounds/plains.png",
  "./assets/backgrounds/swamp.png",
  "./assets/backgrounds/throne_room.png",
  "./assets/backgrounds/town1.png",
  "./assets/backgrounds/town2.png",
  "./assets/backgrounds/town3.png",
  "./assets/backgrounds/victory.png",
  "./assets/backgrounds/volcano.png",
  "./assets/backgrounds/wilderness.png",
  "./assets/fx/fx.png",
  "./assets/sprites/abyssal_wraith.png",
  "./assets/sprites/archer.png",
  "./assets/sprites/castle_guard.png",
  "./assets/sprites/demonlord.png",
  "./assets/sprites/demonlord_2.png",
  "./assets/sprites/desert_boss.png",
  "./assets/sprites/desert_brute.png",
  "./assets/sprites/desert_grunt.png",
  "./assets/sprites/desert_skirmisher.png",
  "./assets/sprites/healer.png",
  "./assets/sprites/hero.png",
  "./assets/sprites/hero_dusk.png",
  "./assets/sprites/hero_ember.png",
  "./assets/sprites/hero_tide.png",
  "./assets/sprites/hero_verdant.png",
  "./assets/sprites/mage.png",
  "./assets/sprites/plains_boss.png",
  "./assets/sprites/plains_brute.png",
  "./assets/sprites/plains_grunt.png",
  "./assets/sprites/plains_skirmisher.png",
  "./assets/sprites/rogue.png",
  "./assets/sprites/swamp_boss.png",
  "./assets/sprites/swamp_brute.png",
  "./assets/sprites/swamp_grunt.png",
  "./assets/sprites/swamp_skirmisher.png",
  "./assets/sprites/volcano_boss.png",
  "./assets/sprites/volcano_brute.png",
  "./assets/sprites/volcano_grunt.png",
  "./assets/sprites/volcano_skirmisher.png",
  "./assets/sprites/warrior.png",
  "./assets/sprites/wilderness_boss.png",
  "./assets/sprites/wilderness_brute.png",
  "./assets/sprites/wilderness_grunt.png",
  "./assets/sprites/wilderness_skirmisher.png",
  "./fonts/cinzel-latin-500-normal.woff2",
  "./fonts/cinzel-latin-600-normal.woff2",
  "./fonts/cinzel-latin-700-normal.woff2",
  "./fonts/jetbrains-mono-latin-500-normal.woff2",
  "./fonts/jetbrains-mono-latin-700-normal.woff2",
  "./fonts/lora-latin-400-italic.woff2",
  "./fonts/lora-latin-400-normal.woff2",
  "./fonts/lora-latin-500-normal.woff2",
  "./fonts/lora-latin-600-normal.woff2",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./manifest.webmanifest"
];

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' skips the HTTP cache, so a fresh deploy can never be
    // stitched together from a mix of new and ten-minute-old files.
    await cache.addAll(PRECACHE.map(u => new Request(u, {cache: 'reload'})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith('veilfall-') && k !== CACHE)
                          .map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, {ignoreSearch: true});
    if (hit) return hit;
    // Any page request inside the app's folder gets the game, online or not.
    if (req.mode === 'navigate') {
      const shell = await cache.match('./index.html');
      if (shell) return shell;
    }
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    } catch (e) {
      return new Response('', {status: 504, statusText: 'Offline'});
    }
  })());
});
