#!/usr/bin/env python3
"""Build the Veilfall offline web app (PWA) from the game source.

    python3 build_pwa.py --html veilfall.html --assets assets --fonts FONTDIR --out veilfall-pwa

Inputs
  --html    the game, exactly as developed (single HTML file, assets referenced
            as 'assets/...' through ASSET_MANIFEST)
  --assets  the assets/ folder (backgrounds/ and sprites/ PNGs)
  --fonts   folder containing the @fontsource woff2 files (latin subsets)
  --out     output folder: push its CONTENTS to the GitHub Pages repo

What it does to the HTML (nothing else in the game changes)
  * swaps the Google Fonts @import for local @font-face rules, so the page
    never reaches for the network
  * adds the manifest, iOS home-screen meta tags and the touch icon
  * adds notch-safe padding for standalone mode on iPhone
  * registers ./sw.js (skipped on file://, so opening the HTML directly still works)

The service worker precaches every file in the output, and its cache name is
a hash of all of them, so any change to any file ships as a new version.
"""
import argparse, hashlib, json, os, re, shutil, sys
from pathlib import Path

FONT_FACES = [
    # family, weight, style, file
    ('Cinzel', 500, 'normal', 'cinzel-latin-500-normal.woff2'),
    ('Cinzel', 600, 'normal', 'cinzel-latin-600-normal.woff2'),
    ('Cinzel', 700, 'normal', 'cinzel-latin-700-normal.woff2'),
    ('Lora', 400, 'normal', 'lora-latin-400-normal.woff2'),
    ('Lora', 500, 'normal', 'lora-latin-500-normal.woff2'),
    ('Lora', 600, 'normal', 'lora-latin-600-normal.woff2'),
    ('Lora', 400, 'italic', 'lora-latin-400-italic.woff2'),
    ('JetBrains Mono', 500, 'normal', 'jetbrains-mono-latin-500-normal.woff2'),
    ('JetBrains Mono', 700, 'normal', 'jetbrains-mono-latin-700-normal.woff2'),
]

HEAD_EXTRA = """<meta name="theme-color" content="#0b0c1e">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Veilfall">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">
<link rel="apple-touch-icon" href="icons/apple-touch-icon.png">
<link rel="preload" href="fonts/cinzel-latin-700-normal.woff2" as="font" type="font/woff2" crossorigin>
<link rel="preload" href="fonts/lora-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
"""

# Launched from the home screen with a translucent status bar, the page runs
# up under the clock and the notch. The stage already has generous padding;
# this only makes sure it is never LESS than the safe area.
SAFE_AREA_CSS = """
/* ---------- installed app (PWA) ---------- */
.stage{
  padding-top:max(2.5rem, calc(env(safe-area-inset-top) + 0.75rem));
  padding-left:max(1rem, env(safe-area-inset-left));
  padding-right:max(1rem, env(safe-area-inset-right));
  padding-bottom:max(4rem, calc(env(safe-area-inset-bottom) + 2rem));
}
html{ -webkit-text-size-adjust:100%; }
body{ -webkit-tap-highlight-color:transparent; }
"""

SW_REGISTER = """<script>
/* Offline support. Registered only when served over http(s) — opening the
   file straight from disk keeps working exactly as before, just without the
   offline cache. */
(function(){
  if(!('serviceWorker' in navigator) || location.protocol === 'file:') return;
  window.addEventListener('load', function(){
    navigator.serviceWorker.register('./sw.js').catch(function(e){
      console.warn('Veilfall: offline cache unavailable', e);
    });
    // Ask the browser not to evict saves under storage pressure. Home-screen
    // apps on iOS are already exempt from Safari's 7-day storage cap; this
    // covers everything else. Harmless if refused.
    if(navigator.storage && navigator.storage.persist){
      navigator.storage.persist().catch(function(){});
    }
  });
})();
</script>
"""

SW_TEMPLATE = r"""/* Veilfall service worker — generated by build_pwa.py, do not hand-edit.
   Cache-first for everything: the game is a fixed set of files and must run
   with no network at all. A new deploy changes this file (the version below is
   a hash of every file), the browser notices on the next online launch,
   installs the new set alongside the old one, and switches over. */
const VERSION = '__VERSION__';
const CACHE = 'veilfall-' + VERSION;
const PRECACHE = __PRECACHE__;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // cache:'reload' skips the HTTP cache, so a fresh deploy can never be
    // stitched together from a mix of new and ten-minute-old files.
    await cache.addAll(PRECACHE.map(u => new Request(u, {cache: 'reload'})));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k.startsWith('veilfall-') && k !== CACHE)
                          .map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req, {ignoreSearch: true});
    if (hit) return hit;
    // Any page request inside the app's folder gets the game, online or not.
    if (req.mode === 'navigate') {
      const shell = await cache.match('./index.html');
      if (shell) return shell;
    }
    try {
      const res = await fetch(req);
      if (res && res.ok && res.type === 'basic') cache.put(req, res.clone());
      return res;
    } catch (e) {
      return new Response('', {status: 504, statusText: 'Offline'});
    }
  })());
});
"""


def font_face_css():
    rules = []
    for fam, w, style, fn in FONT_FACES:
        rules.append("@font-face{font-family:'%s';font-style:%s;font-weight:%d;"
                     "font-display:swap;src:url('fonts/%s') format('woff2');}" % (fam, style, w, fn))
    return "\n".join(rules)


def transform_html(src: str) -> str:
    imp = re.compile(r"@import url\('https://fonts\.googleapis\.com/[^']*'\);")
    if len(imp.findall(src)) != 1:
        sys.exit("expected exactly one Google Fonts @import in the HTML")
    out = imp.sub(lambda m: font_face_css(), src)

    vp = '<meta name="viewport" content="width=device-width, initial-scale=1.0">'
    if vp not in out:
        sys.exit("viewport meta not found")
    out = out.replace(vp, '<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">\n' + HEAD_EXTRA, 1)

    if out.count('</style>') < 1:
        sys.exit("no </style> found")
    i = out.index('</style>')
    out = out[:i] + SAFE_AREA_CSS + out[i:]

    j = out.rindex('</body>')
    out = out[:j] + SW_REGISTER + out[j:]

    if 'fonts.googleapis' in out or 'fonts.gstatic' in out:
        sys.exit("a Google Fonts reference survived the rewrite")
    if re.search(r"""(?:src|href)=["']https?://""", out):
        sys.exit("the HTML still references a remote URL")
    return out


def make_icons(out: Path, sprite: Path):
    from PIL import Image, ImageDraw
    icons = out / 'icons'
    icons.mkdir(parents=True, exist_ok=True)
    sheet = Image.open(sprite).convert('RGBA')
    frame = sheet.width // 4
    fig = sheet.crop((0, 0, frame, frame))          # idle, frame 1
    bbox = fig.getbbox() or (0, 0, frame, frame)
    fig = fig.crop(bbox)

    def render(size, safe):
        """safe = fraction of the canvas the figure may occupy."""
        img = Image.new('RGBA', (size, size), (11, 12, 30, 255))
        d = ImageDraw.Draw(img)
        # soft gold halo behind the figure
        for r in range(int(size * 0.46), 0, -max(1, size // 128)):
            a = int(70 * (1 - r / (size * 0.46)))
            d.ellipse([size/2 - r, size*0.52 - r, size/2 + r, size*0.52 + r], fill=(224, 182, 84, a))
        img = Image.alpha_composite(Image.new('RGBA', (size, size), (11, 12, 30, 255)), img)
        scale = max(1, int(size * safe / max(fig.width, fig.height)))   # whole-number scale: crisp pixels
        f = fig.resize((fig.width * scale, fig.height * scale), Image.NEAREST)
        img.alpha_composite(f, ((size - f.width) // 2, (size - f.height) // 2 + int(size * 0.02)))
        return img.convert('RGB')

    render(180, 0.78).save(icons / 'apple-touch-icon.png')
    render(192, 0.78).save(icons / 'icon-192.png')
    render(512, 0.78).save(icons / 'icon-512.png')
    render(512, 0.56).save(icons / 'icon-maskable-512.png')   # Android crops maskable icons to a circle


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--html', required=True)
    ap.add_argument('--assets', required=True)
    ap.add_argument('--fonts', required=True)
    ap.add_argument('--out', required=True)
    ap.add_argument('--license', nargs='*', default=[], help='OFL license file(s) to ship beside the fonts')
    a = ap.parse_args()

    out = Path(a.out)
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    src = Path(a.html).read_text(encoding='utf-8')
    (out / 'index.html').write_text(transform_html(src), encoding='utf-8')

    # assets: copy what the manifest asks for, and report what is missing
    m = re.search(r'/\* ASSET-MANIFEST-START \*/\s*const ASSET_MANIFEST = (\{.*?\});\s*/\* ASSET-MANIFEST-END \*/', src, re.S)
    manifest = json.loads(m.group(1))
    wanted = list(manifest['backgrounds'].values()) + list(manifest['sprites'].values())
    if manifest.get('fx'):
        wanted.append(manifest['fx']['sheet'])          # the combat effects sheet
    missing = []
    for rel in wanted:
        s = Path(a.assets) / rel
        if s.exists():
            d = out / 'assets' / rel
            d.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(s, d)
        else:
            missing.append(rel)

    fonts = out / 'fonts'
    fonts.mkdir()
    for *_, fn in FONT_FACES:
        hits = list(Path(a.fonts).rglob(fn))
        if not hits:
            sys.exit('font not found: ' + fn)
        shutil.copy2(hits[0], fonts / fn)
    if a.license:
        (fonts / 'OFL.txt').write_text('\n\n' .join(Path(l).read_text(encoding='utf-8').strip() for l in a.license) + '\n', encoding='utf-8')

    hero = Path(a.assets) / 'sprites' / 'hero.png'
    make_icons(out, hero)

    (out / 'manifest.webmanifest').write_text(json.dumps({
        "name": "Veilfall — An Isekai Chronicle",
        "short_name": "Veilfall",
        "description": "A pixel-art isekai RPG. Plays fully offline once installed.",
        "start_url": "./",
        "scope": "./",
        "display": "standalone",
        "orientation": "any",
        "background_color": "#0b0c1e",
        "theme_color": "#0b0c1e",
        "icons": [
            {"src": "icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "icons/icon-512.png", "sizes": "512x512", "type": "image/png"},
            {"src": "icons/icon-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}
        ]
    }, indent=2, ensure_ascii=False), encoding='utf-8')

    (out / '.nojekyll').write_text('')

    # precache list = every file we ship except the worker itself
    files = sorted(p.relative_to(out).as_posix() for p in out.rglob('*')
                   if p.is_file() and p.name not in ('sw.js', '.nojekyll', 'OFL.txt'))
    h = hashlib.sha256()
    for f in files:
        h.update(f.encode()); h.update((out / f).read_bytes())
    version = h.hexdigest()[:12]
    precache = ['./'] + ['./' + f for f in files]
    sw = SW_TEMPLATE.replace('__VERSION__', version).replace('__PRECACHE__', json.dumps(precache, indent=2))
    (out / 'sw.js').write_text(sw, encoding='utf-8')

    print(f'built {out}  version {version}  files {len(precache)}')
    if missing:
        print(f'WARNING: {len(missing)} asset(s) named in the game are not in {a.assets}:')
        for r in missing:
            print('   ', r)
    return 0


if __name__ == '__main__':
    sys.exit(main())
